### ISSUE TITLE
Paginated does not contain current page number information.

### ISSUE THREAD

**Issue by tokuhirom** [tokuhirom/tinyorm#9]
It's not useful!!!!!!!!!!!!!!!!!!

**Comment by moznion** [comment]
:tired_face:

**Comment by tokuhirom** [comment]
Ah, no. I thought the pagination logic should be `?lastId=XXX` instead of `?page=XXX`.

**Comment by tokuhirom** [comment]
Then, the pager class shouldn't have current page!
